### ISSUE TITLE
Failed to exec env script

### ISSUE THREAD

**Issue by keerthivasan-r** [ngx-rocket/scripts#20]
*Environment*
ngX-Rocket: 8.1.1
Node.js: v10.22.0
Npm: 6.14.6
OS: win32 x64 10.0.18363

*Error stack trace*
 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error ng-x-rocket@1.0.0 env: `ngx-scripts env npm_package_version`
22 error Exit status 1
23 error Failed at the ng-x-rocket@1.0.0 env script.
23 error This is probably not a problem with npm. There is likely additional logging output above.

_Note : I use nvm - 1.1.7 to manage node installations_

**Comment by sinedied** [comment]
I cannot seem to reproduce this one, could you paste the result of `npx ngx-scripts env npm_package_version` ?
