### ISSUE TITLE
I can't get it to build with --env=dev

### ISSUE THREAD

**Issue by enhendrickson** [ngx-rocket/scripts#7]
I apologize for being a squeaky wheel but I have run the following commands and I can't get the angular side of my app to build in development environment.  It's always prod config.  

npm run cordova:build -- --env=dev --device --debug 
npm run cordova build  --device --debug -- --env=dev
npm run cordova build  --device --debug --env=dev

In several of the version of the above, I saw something complaining that 
    Unknown option: '--env'

What am I doing wrong?

**Comment by sinedied** [comment]
No need to apologize, thanks to you I just discovered that they replaced `--env` by `--configuration`, among other breaking changes in angular-cli 6 that were not documented 😞 

So I need to change the flag in ngx-script too, I'll push a fix ASAP

**Comment by sinedied** [comment]
I just published version `3.0.0` to NPM, so you just have to `npm i ngx-scripts@latest` in your project 😉 
Had to make it a major version bump since I changed the `--env` option to `--configuration` to match angular/cli new behavior.

**Comment by enhendrickson** [comment]
This should work, right?  
`ngx-scripts cordova build --device --debug -- --configuration=dev`

It doesn't.  It still uses production.

**Comment by sinedied** [comment]
@enhendrickson Angular CLI changed the way it works, the `--configuration` flag does not behave the same as the previous `--environment` flag: it now selects a whole build configuration defined in `angular.json`, not just the environment file.
And by default you have one for `production`, but not for dev, so you have 2 options here:

- use the `--dev` flag of ngx-scripts that bascially set the `--prod=false` flag on Angular CLI, ie: `ngx-scripts cordova build --dev --device --debug`, but it will also disable minifications and code optiomization beside changing the environment

- create a new `dev` configuration in `angular.json` that extends the existing `production` one but with a different enviromnent file, and then your command will work.

Yes, that's a lot of bother for something that just used to work 😞

**Comment by enhendrickson** [comment]
@sinedied thanks for the awesome explanation!!
